import { FileType, Transformer } from "../../types";

const GENERATED_BY = `/** Generated by rtcTransformer **/`;

export const transformRtc: Transformer = (context) => {
  const file = context.getOrCreateFile("main.c", FileType.SOURCE);

  file.includes.push("#include <iostream>");
  file.defines.push('#define HELLO_WORLD "Hello, world!"');
  file.functions.push(
    [GENERATED_BY, "int test() {", "  printf(HELLO_WORLD);", "}", ""].join("\n")
  );

  file.main.push([GENERATED_BY, "  test();", ""].join("\n"));

  return context;
};
